# Generated by Django 4.2.7 on 2023-11-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watermarkedvideo",
            name="custom_coordinate_X",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="watermarkedvideo",
            name="custom_coordinate_Y",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="watermarkedvideo",
            name="lazy_position",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="watermarkedvideo",
            name="scale",
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=3),
        ),
    ]
